import { createRoot } from 'react-dom/client'
import App from './App.tsx'
import './index.css'

createRoot(document.getElementById("root")!).render(<App />);
// PWA: register service worker generated by vite-plugin-pwa
// This import is replaced at build time
import { registerSW } from 'virtual:pwa-register'
registerSW({ immediate: true })
