// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjvkkyxfbknabzncxwab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqdmtreXhmYmtuYWJ6bmN4d2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTMzOTksImV4cCI6MjA2NDM2OTM5OX0.tojJIBK0g9e0mI5ktJJSV6CSvD4rQxG0lrwBNDFP0Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);